### ISSUE TITLE
Safary issue with generated CSV

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/cakephp-csvview#103]
chrome and FF work nicely, but on safari the content is scrambled somehow:
```
bplist00Ñ_WebMainResourceÕ	
_WebResourceMIMEType_WebResourceTextEncodingName^WebResourceURL_WebResourceFrameName_WebResourceDataXtext/csvUUTF-8_:https://domain/controller/in-progress.csvPOOn<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">"Issue","Group",Title,"Status",Priority,Link,Created,Modified
[payload]
</pre></body></html>\00\00\00\00(\00>\00\\00k\00\00\00\00£\00à\00á\00\00\00\00\00\00\00\00\00\00\00\00\00
\00\00\00\00\00\00\00\00\00\00\00\00\00\00PS
```

[payload] is the actual rows of data I removed for simplicity

the other browsers also auto trigger download, this one doesnt.
Is this a known issue to others?

**Comment by josegonzalez** [comment]
Thats strange, what happens when you curl the data? We might need to set special headers for safari to not garble it.

**Comment by dereuromark** [comment]
It wasnt my PC, but a co worker. As such I cant reproduce easily right now.
I will close it for the time being until someone can produce more debug info etc.
