### ISSUE TITLE
csvView save only html code

### ISSUE THREAD

**Issue by dgtlslave** [FriendsOfCake/cakephp-csvview#105]
Hi, I have little problem. CsvView save in csv file only html code, something like that:` <!DOCTYPE html>` ... and whole page... Help pls. What did I miss?
Thks

**Comment by dgtlslave** [comment]
`public function export() {
		$this->response->download('export.csv');
        $data = [
            ['a', 'b', 'c'],
            [1, 2, 3],
            ['you', 'and', 'me'],
        ];
        $_serialize = 'data';
        $this->set(compact('data', '_serialize'));
        $this->viewBuilder()->className('CsvView.Csv');
        return;
	}`

**Comment by dgtlslave** [comment]
`Router::extensions(['csv']);`

**Comment by dgtlslave** [comment]
And when I try to start function with uncommeted '_ext' => 'csv' I have an error: Error: Create ProjectsController::export.csv() in file: src/Controller/ProjectsController.php.
Above is my button.
`<?= $this->Html->link('save', [
        'controller' => 'Projects', 
        'action' => 'export',
        // '_ext' => 'csv'
        ],

        ['class' => 'btn btn-success']) 
      ?>`

**Comment by dgtlslave** [comment]
@dereuromark can you help me? Sorry for the taking time )

**Comment by dereuromark** [comment]
If the docs are unclear here, you can also compare yours with [sandbox](https://sandbox.dereuromark.de/sandbox/csv) code, what you might have missed.

**Comment by dgtlslave** [comment]
Thanks. The problem is plugin insert Router::extensions(['csv']); like last row in my routes.php  
When I picked up row with csv routes plugin start to work correct

**Comment by dereuromark** [comment]
Anything to improve the docs of this plugin here? Otherwise you can close this ticket then.
