### ISSUE TITLE
Missing template in export

### ISSUE THREAD

**Issue by javi-villa** [FriendsOfCake/cakephp-csvview#112]
My version of Cakephp is 3.7.9

I am trying to export in a CSV file a content, for example:

`public function export()
{
    $data = [
        ['a', 'b', 'c'],
        [1, 2, 3],
        ['you', 'and', 'me'],
    ];
    $_serialize = 'data';

    $this->viewBuilder()->setClassName('CsvView.Csv');
    $this->set(compact('data', '_serialize'));
}`

If I access to /controller/export then I have the error message "Missing template export.ctp".
If I access to /controller/export.csv then I have the error message 404.

Thanks.

**Comment by javi-villa** [comment]
It was a problem in my configuration...not in plugin.

**Comment by miguelxt** [comment]
> It was a problem in my configuration...not in plugin.

How did you solve it?
