### ISSUE TITLE
Extending the CsvView class and RequestHandler

### ISSUE THREAD

**Issue by larsgw** [FriendsOfCake/cakephp-csvview#127]
I am using CsvView, but I have to pre-process the data before serialization. Given the amount of code involved, I thought I'd put it in a separate view class rather than using `_extract`. However, when I point CSV in the `viewClassMap` to my custom view class, the value gets overwritten by this plugin.

https://github.com/FriendsOfCake/cakephp-csvview/blob/3b105f472e459aff20c769cf6f932d4b5e0638f0/config/bootstrap.php#L11-L16

I can make a PR to check whether the config is set before overriding it, would that be reasonable for the project? Something like this.

```php
if ($controller->components()->has('RequestHandler') &&
    $controller->RequestHandler->getConfig('viewClassMap.csv') === null) { 
    $controller->RequestHandler->setConfig('viewClassMap.csv', 'CsvView.Csv'); 
}
```

**Comment by ADmad** [comment]
You can simply skip loading the bootstrap by using `'bootstrap' => false` option when loading the plugin.

**Comment by larsgw** [comment]
Ah, that works. Thank you!
