### ISSUE TITLE
support for cakephp 4

### ISSUE THREAD

**Issue by robots** [FriendsOfCake/cakephp-csvview#128]
Hi,

could you please add support for cake php 4.x ? Composer will refuse to load this repository.

> 
>  Problem 1
>    - Installation request for friendsofcake/cakephp-csvview ^3.4 -> satisfiable by friendsofcake/cakephp-csvview[3.4.0].
>    - friendsofcake/cakephp-csvview 3.4.0 requires cakephp/cakephp ^3.5.5 -> satisfiable by cakephp/cakephp[3.5.10, 3.5.11, 3.5.12, 3.5.13, 3.5.14, 3.5.15, 3.5.16, 3.5.17, 3.5.18, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9, 3.6.0, 3.6.0-RC1, 3.6.0-RC2, 3.6.0-beta1, 3.6.0-beta2, 3.6.0-beta3, 3.6.1, 3.6.10, 3.6.11, 3.6.12, 3.6.13, 3.6.14, 3.6.15, 3.6.2, 3.6.3, 3.6.4, 3.6.5, 3.6.6, 3.6.7, 3.6.8, 3.6.9, 3.7.0, 3.7.0-RC1, 3.7.0-RC2, 3.7.0-RC3, 3.7.0-beta1, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.7.7, 3.7.8, 3.7.9, 3.8.0, 3.8.0-RC1, 3.8.0-RC2, 3.8.0-RC3, 3.8.0-beta1, 3.8.1, 3.8.10, 3.8.11, 3.8.12, 3.8.13, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.8.7, 3.8.8, 3.8.9, 3.9.0, 3.9.0-RC1, 3.9.0-RC2, 3.9.1, 3.x-dev] but these conflict with your requirements or minimum-stability.

thanks

**Comment by dereuromark** [comment]
@ADmad It is probably time for a stable release :)

**Comment by ADmad** [comment]
CakePHP 4 compatible stable release done.
