### ISSUE TITLE
Deprecation warning with CakePHP 4.3

### ISSUE THREAD

**Issue by matteorebeschi** [FriendsOfCake/cakephp-csvview#138]
I am running CakePHP 4.3.11 and cakephp-csvview 4.1.0.

When I use the CsvView in my code, I get this:

[Deprecated (16384)](javascript:void(0);): Setting special view var "_header" is deprecated. Use ViewBuilder::setOption('header', $value) instead.
/var/www/repo/public/vendor/friendsofcake/cakephp-csvview/src/View/CsvView.php, line: 200

**Comment by dereuromark** [comment]
Error message contains the solution it seems, closing then.
