### ISSUE TITLE
exported/downloaded files missing .csv extension

### ISSUE THREAD

**Issue by ThomasRalee** [FriendsOfCake/cakephp-csvview#36]
Hi, 

The files i exported are missing the .csv extensions. Am i doing something wrong?
This is the codes i use to test the function. 

```
public function export() {
    $data = array(
        array('a', 'b', 'c'),
        array(1, 2, 3),
        array('you', 'and', 'me'),
    );
    $_serialize = 'data';

    $this->viewClass = 'CsvView.Csv';
    $this->set(compact('data', '_serialize'));
}
```

**Comment by vikastyagi87** [comment]
Add 1 more line like below-
```
$this->response->download('export.csv'); 
$this->viewClass = 'CsvView.Csv';
$this->set(compact('data', '_serialize'));
```

**Comment by dereuromark** [comment]
This can easily be resolved by using the correct URL right away, so only allow access via

    /controller/export.csv

Then it will use the right file name even without that header set.
