### ISSUE TITLE
Feature Request: Provide a "map" Feature For Extracted Array Values

### ISSUE THREAD

**Issue by ojtibi** [FriendsOfCake/cakephp-csvview#37]
Before returning/displaying values extracted from a model-generated array into the output CSV, it would be nice to use a mapping function on each value for pre-processing.

For example: Usually, records with dates are stored in the database as GMT, but we want to convert these dates to the end-user's timezone on the CSV output. The $_extract view variable may be extended in a way to like so: `'Model.field' => 'callableFunction'`, where `callableFunction()` will be applied to values extracted from `Model.field` and sent as final output.

**Comment by josegonzalez** [comment]
@dereuromark what about this?

**Comment by dereuromark** [comment]
A new functionality would always be BC IMO.
But I am not sure if this is needed or could already be done with the tools at hand inside the model/controller layer.
What do you think?

**Comment by dereuromark** [comment]
@ojtibi Do you have an example or some code to share? A PR would be best, but you can also just post it here.

**Comment by beporter** [comment]
I don't think it necessarily has to be a breaking change. Instead of passing a function name, pass the actual callable. For example:

```php
$_extract = [
   // "Simple" export as before: extracts the row's "id" field.
  'ID' => 'id',

  // Inline closure example.
  'Closure Column' => function ($row) {
    return sprintf('%s (%s) %s', $row->title, $row->detail, $row->is_active ? 'Yes' : 'No');
  },

  // The callable must take a $row as single arg.
  'Alternate Callable Form' => [$object, 'methodName'],

  // However! This is the potential conflict for backwards compatibility!
  'Static Callable Form' => 'ClassName::method', 
  // It's conceivable that someone might have a field name that ends up matching a PHP function.
  'Field Name Overlaps PHP Function' => 'basename',
];
```

The code in this plugin might only need to add an `if (is_callable($extract)) { ... }` check [somewhere around here maybe](https://github.com/FriendsOfCake/cakephp-csvview/blob/ac9ed2e20dc13f6a636128c33701c0dc8334f430/src/View/CsvView.php#L303)? I don't know that I have time for a PR, but could try.

**Comment by josegonzalez** [comment]
@beporter go for it :)
