### ISSUE TITLE
CakePHP 3

### ISSUE THREAD

**Issue by rrd108** [FriendsOfCake/cakephp-csvview#39]
Do you have plans for CakePHP 3.0?

**Comment by josegonzalez** [comment]
https://github.com/FriendsOfCake/cakephp-csvview/tree/2.0

We should probably make that branch default /cc @ADmad

**Comment by ADmad** [comment]
Well at least 1) on the checklist on PR #38 needs to be addressed before that can be done.

**Comment by ionas** [comment]
Is this ticket obsolete now?

**Comment by josegonzalez** [comment]
Yes, 3.x is now master.
