### ISSUE TITLE
Failed to render CSV format

### ISSUE THREAD

**Issue by matrich** [FriendsOfCake/cakephp-csvview#43]
I have my application already running with AuthUser component and after installation of cakephp-csvview and copying the first example. I am getting this error. 

Do I have to create a layout and view to handle the csv format like it is for pdf or what could be causing this error?

Error: Fatal Error (256): [Cake\View\Exception\MissingHelperException] Helper class AuthUserHelper could not be found.
#0 C:\wamp\www\...\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php(91): Cake\View\HelperRegistry->_throwMissingClassError('AuthUser', NULL)
#1 C:\wamp\www\...\vendor\cakephp\cakephp\src\View\HelperRegistry.php(67): Cake\Core\ObjectRegistry->load('AuthUser')
#2 C:\wamp\www\...\vendor\cakephp\cakephp\src\View\View.php(745): Cake\View\HelperRegistry->__isset('AuthUser')
#3 C:\wamp\www\...\src\Template\Element\top_bar.ctp(53): Cake\View\View->__get('AuthUser')
#4 C:\wamp\www\...\vendor\cakephp\cakephp\src\View\View.php(828): include('C:\\wamp\\www\\rig...')
#5 C:\wamp\www\...\vendor\cakephp\cakephp\src\View\View.php(788): Cake\View\View->_evaluate('C:\\wamp\\www\\rig...', Array)
#6 C:\wamp\www\...\vendor\cakephp\cakephp\src\View\View.php(1155): Cake\View\View->_render('C:\\wamp\\www\\rig...', Array)
#7 C:\wamp\www\...\vendor\cakephp\cakephp\src\View\View.p in [C:\wamp\www\...\vendor\cakephp\cakephp\src\Error\ErrorHandler.php, line 157]

**Comment by josegonzalez** [comment]
Seems like its falling back to your default view because you never set `_serialize`. As I don't see CsvView in that stacktrace, I don't think this is an error in our library.
