### ISSUE TITLE
Upgrade which version of the core this requires

### ISSUE THREAD

**Issue by patrickconroy** [FriendsOfCake/cakephp-csvview#45]
Would it be possible to get a branch in this repo that requires dev-master? I have an app that uses ~3.1 instead of ~3.0 and right now they're incompatible.

Thanks
cc @josegonzalez

**Comment by dereuromark** [comment]
@patrickconroy How come? 3.1 is stable, so the requirement ~3.0 should give you both in 3.1 just fine.

**Comment by patrickconroy** [comment]
Ah thanks. Sorry I should have been more clear.. when trying to use the core `dev-master`, I get this error:

``
    - friendsofcake/cakephp-csvview 2.0.0 requires cakephp/cakephp ~3.0 -> satisfiable by cakephp/cakephp[3.0.0, 3.0.0-RC1, 3.0.0-RC2, 3.0.0-alpha1, 3.0.0-alpha2, 3.0.0-beta1, 3.0.0-beta2, 3.0.0-beta3, 3.0.1, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.0-RC1, 3.1.0-beta, 3.1.0-beta2, 3.1.1, 3.2.x-dev].
``

Since this and other plugins seem to prefer ~3.0 instead of dev-master I'll go with that in my requirement of the core too.
