### ISSUE TITLE
Date fields exported as NULL

### ISSUE THREAD

**Issue by quecosa65** [FriendsOfCake/cakephp-csvview#46]
Everything works great but, date fields are exported as NULL
Any advise would be really apreciated :D

Here is the table:
![table](https://cloud.githubusercontent.com/assets/12212382/10417683/9d16037e-700a-11e5-86b3-df3aefcb2ec8.jpg)

Here is the exported file, check out fecha_de_ingreso field as NULL:
![error](https://cloud.githubusercontent.com/assets/12212382/10417687/bdebd09c-700a-11e5-9201-901259a70657.jpg)

Here is the mysql workbench screenshot of the table:
![mysql](https://cloud.githubusercontent.com/assets/12212382/10417706/171047c0-700b-11e5-92eb-e8a366f1b15c.jpg)

Here is my code:
```php
public function export() {
    $kids = $this->Kids->find()->where(['user_id'=>$this->Auth->user('id')]);
        $_serialize = 'kids';
        $_bom = true;
        $this->response->download('CONTROL_NIÑOS.csv');
        $this->viewClass = 'CsvView.Csv';
        $this->set(compact('kids', '_serialize', '_bom'));
    }

**Comment by kyleweishaupt** [comment]
I'm on the same page. Having trouble getting DATETIMES to export as well.

**Comment by josegonzalez** [comment]
Maybe its not being casted to a string properly?

**Comment by kyleweishaupt** [comment]
I got around this for now by creating a virtual field in my entity that returned as a string:

`    protected function _getCreatedString()
`    {
`        return (string) $this->_properties['created']; 
`    } 

Then I just used the `created_string` property with `$_extract` and it worked.

**Comment by josegonzalez** [comment]
What is the type of that field? Perhaps CsvView should cast everything to a string before exporting, though that might slow down performance.

**Comment by kyleweishaupt** [comment]
The `created` field is the typical nullable `DATETIME` that's compatible with the Timestamp behavior.

**Comment by aguirre1017** [comment]
Hi @kyleweishaupt how can I properly used the added virtual field at $_extract? Can you please post a sample code? Your above suggestion does not work as expected.

**Comment by dereuromark** [comment]
I found the issue and will provide a fix in a few minutes.

PS: Any idea why the default for NULL columns is actually `'NULL'`? Shouldnt it rather be empty string?
Overwriting this every time is kind of a PITA.

**Comment by kyleweishaupt** [comment]
@aguirre1017 All I did was add the name of the virtual field in the `$_extract` array. Here's what mine looks like:

````php
$_extract = [
'id', 
'user.full_name', 
'name',
'email',
'notes',
'follow_up_date_timestamp',
'created_timestamp',
'modified_timestamp'
];
````

So instead of using just the `created` field, I used `created_timestamp` that is being created in the entity class. 

Here is the code in my entity:

````php
protected $_virtual = [
	'follow_up_date_timestamp',
	'created_timestamp',
	'modified_timestamp'
];		

protected function _getFollowUpDateTimestamp()
{
	return (!empty($this->_properties['follow_up_date'])) ? (string) $this->_properties['follow_up_date'] : null;
}

protected function _getCreatedTimestamp()
{
	return (!empty($this->_properties['created'])) ? (string) $this->_properties['created'] : null;
} 

protected function _getModifiedTimestamp()
{
	return (!empty($this->_properties['modified'])) ? (string) $this->_properties['modified'] : null;
}
````

Hope this helps for you!

**Comment by dereuromark** [comment]
This is a nice hack, but quite some overhead for an issue that maybe could be fixed in a more central place. Imagine you want to export multiple tables/entities.

**Comment by dereuromark** [comment]
Resolved with my PR https://github.com/FriendsOfCake/cakephp-csvview/issues/55 .
