### ISSUE TITLE
UTF-8 BOM

### ISSUE THREAD

**Issue by kicaj** [FriendsOfCake/cakephp-csvview#52]
The solution for open CSV file with dingbats characters in Microsoft Excel is add special characters before return: 

Line 158:
`return "\xEF\xBB\xBF" . $this->_serialize();`

**Comment by josegonzalez** [comment]
Can you explain what it is you are trying to do here?

**Comment by kicaj** [comment]
I use Your code, I get data from database (mysql/utf8_general_ci) and create .csv file. Afer I can't open in Microsoft Excel but can in Calc OpenOffice.

Problem was in some records, it has dingbats characters, like ❤

**Comment by dereuromark** [comment]
Isnt that what _bom option already does?
https://github.com/FriendsOfCake/cakephp-csvview/blob/master/src/View/CsvView.php#L350
Did you try it with that?

**Comment by kicaj** [comment]
Yes, that's it! Thanks!
