### ISSUE TITLE
Tagged versions

### ISSUE THREAD

**Issue by ionas** [FriendsOfCake/cakephp-csvview#58]
Is there any plan to setup a semver/tagged/stable version that one could link to from production and be fine with being BC (for instance BC with cakephp 3.1 or 3.2 etc)?

Right now you cannot composer upgrade without being fearful only composer install the fixed version.

**Comment by dereuromark** [comment]
When https://github.com/FriendsOfCake/cakephp-csvview/pull/57 is merged and we have a 3.0 version we can follow strict semvar I imagine.

**Comment by dereuromark** [comment]
Anything else we should/want to skip before declaring a new 3.0.0 version?

**Comment by dereuromark** [comment]
3.0 release done.
