### ISSUE TITLE
CsvView falls over when presented with models with relations

### ISSUE THREAD

**Issue by mozillamonks** [FriendsOfCake/cakephp-csvview#61]
You'll get a lovely screen of "Notice (8): Array to string conversion [ROOT/vendor/friendsofcake/cakephp-csvview/src/View/CsvView.php, line 376]" if you try to use this plugin with a model that's been configured with relationships. The plugin needs to learn to flatten these.

**Comment by josegonzalez** [comment]
When you use models with relations, you're expected to use the `_serialize` option to pull out the data you want. 

I didn't want to "automatically" pull out the data, since it gets pretty weird when you start getting into multiple levels of relationships, and probably best handled by the user with the aforementioned option.

Does that explanation help?

**Comment by mozillamonks** [comment]
Somewhat, although I don't see how to pull out data with _serialize, I'd played a bit with _extract but didn't seem to get the correct result either. Would you be kind enough as to provide an example?

**Comment by josegonzalez** [comment]
oh sorry yeah, `_extract`. Basically It's the same syntax as `Hash::get()`, so anything that works there works here.

Do you have an example entity/relation set that you can provide and the `_extract` code you used? We can help set you straight if we know what you're dealing with.

**Comment by mozillamonks** [comment]
So, I think I found what I was doing wrong but I'm not sure this is correct still.

I have set up the parseExtensions version (which, sound be Router::extensions I realized after trial and error) from the README. My controller has:

```
    public $components = [
        'RequestHandler' => [
            'viewClassMap' => ['csv' => 'CsvView.Csv']
        ]
    ];
```

and my function is:
```
    public function staff()
    {
        $this->paginate = [
            'contain' => ['Users', 'Conventions']
        ];

        $query = $this->People->find();
        $query->where(['role !=' => 6]);

        $this->set('people', $this->paginate($query));
        $this->set('_serialize', ['people']);
        $this->set('_extract', ['id', 'name', 'convention.name']);
    }
```

This works! It feels like _extract should be ['Person.id', 'Person.name', 'Convention.name'], which is what the readme shows and what had messed me up before.

**Comment by josegonzalez** [comment]
Ah! Okay, the readme is definitely a bit wrong, and is using the array conventions from 2.x instead of the `toArray` output in 3.x. Can you file a PR against the readme, updating it to remove the extra table prefix, and normalizing the capitalization?

**Comment by mozillamonks** [comment]
Sure!
