### ISSUE TITLE
Getting view error on cakePHP 3.2

### ISSUE THREAD

**Issue by angelomercado** [FriendsOfCake/cakephp-csvview#63]
any body knows the issue here?

Error: CsvView.Csv could not be found.

Error: Create the class CsvView.Csv below in file: src\View\CsvView.Csv.php

I've put the csvview plugin under  myproject/plugins since Im using cakephp 3.2

**Comment by josegonzalez** [comment]
Did you install the plugin via composer?

**Comment by angelomercado** [comment]
I just copied the csvview plugin going to directory /plugins and enable it using bootstrap?

**Comment by angelomercado** [comment]
also, if I use composer in my project directory will it not raise errors since Im using the latest version of cakePHP?

**Comment by josegonzalez** [comment]
You should install it via composer as [mentioned in our documentation](https://github.com/FriendsOfCake/cakephp-csvview#installation).

**Comment by angelomercado** [comment]
thanks, but will it not cause any error since Im using the latest cakePHP 3.2?

**Comment by josegonzalez** [comment]
It will work fine in 3.2, you just didn't install/enable the plugin properly.

**Comment by angelomercado** [comment]
got it. thanks for the great and faster response.

**Comment by angelomercado** [comment]
so it's working now, while it does not contain .csv extension?

**Comment by josegonzalez** [comment]
Please read the readme, it'll show how to configure the plugin to use/not use csv extensions etc. It is pretty comprehensive and has quite a few different examples. If you need more help, please join either the slack or irc #cakephp rooms.

Happy that your initial installation issues were resolved.
