### ISSUE TITLE
Not support CakePHP 2.X?

### ISSUE THREAD

**Issue by yuchaozh** [FriendsOfCake/cakephp-csvview#66]
Hi,

I am current using CakePHP 2.7.7. Does this library supports CakePHP 2.x?

Thanks in advance.

**Comment by dereuromark** [comment]
See the 1.x releases in https://github.com/FriendsOfCake/cakephp-csvview/releases

**Comment by yuchaozh** [comment]
Thanks Mark,

I use git clone to download CsvView in Plugin directory.
Added "CakePlugin::load('CsvView')" in the bootstrap.php.
Also Added
 ` 
$data = array(
		array('a', 'b', 'c'),
		array(1, 2, 3),
		array('you', 'and', 'me'),
	);
        $_serialize = 'data';
        $this->viewClass = 'CsvView.Csv';
	$this->set(compact('data', '_serialize'));
`
into my controller function. But it shows 

Fatal Error
Error: Class 'CsvView' not found
File: /var/www/html/Corp1/lib/Cake/Controller/Controller.php
Line: 1247

Do you know how to solve this error?

Thanks.

**Comment by yuchaozh** [comment]
Oh, It works now. There is no controller in git clone folder. Thanks for your help!
