### ISSUE TITLE
Composer require fails

### ISSUE THREAD

**Issue by brandtheisey** [FriendsOfCake/cakephp-csvview#69]
Both
```composer require friendsofcake/cakephp-csvview:~2.0```
and
```composer require friendsofcake/cakephp-csvview```

generate an error.

The errors are the same but the specific error for the latter is:

<img width="585" alt="screen shot 2016-06-09 at 11 47 42 am" src="https://cloud.githubusercontent.com/assets/7915386/15936210/1f5b2274-2e38-11e6-9a5b-7c73d9cb6c4a.png">

PHP 5.6.19
Cake v3.2.5

**Comment by josegonzalez** [comment]
Can you try that with `-vvv` on the composer require, and gist the output?

**Comment by brandtheisey** [comment]
Sure here you go: 
https://gist.github.com/brandtheisey/f3efeaf097f21719ced298b6a36d676a

For what it's worth, I have two other people on my team that have same issue.

**Comment by josegonzalez** [comment]
Is that the entire output? Doesn't look like it.

**Comment by brandtheisey** [comment]
You are right, apologies.
(updated)
https://gist.github.com/brandtheisey/f3efeaf097f21719ced298b6a36d676a

**Comment by josegonzalez** [comment]
Can you blow out your composer.lock and clear your composer cache? Seems like this isn't related to cakephp-csvview but something in your app env.

**Comment by brandtheisey** [comment]
I will try that.

**Comment by brandtheisey** [comment]
That fixed it, sorry for wasting your time.

**Comment by josegonzalez** [comment]
Heh no worries! Glad that fixed it :)
