### ISSUE TITLE
Problem with separator

### ISSUE THREAD

**Issue by Cafnio** [FriendsOfCake/cakephp-csvview#75]
Hi there.

First of all, thanks for your job! It's a great addon for cakephp and really helpfull..

Wondering if you can help me out. Basicly, I wanted the csv to work on both apple Numbers and Microsoft Excel. The problem is that apple Numbers use ";" to separate columns, and Microsoft Excel uses "," to separate columns.

Setting the separator, I can make it work on each one of them, but not on both of them.

I got: 
```php
$_setSeparator = true;
$_delimiter = ",";

this->set(compact('_setSeparator', '_header', '_extract', '_delimiter', '_bom', '_null', '_dataEncoding', '_csvEncoding'));
```
Doing anything wrong?

Thanks

**Comment by josegonzalez** [comment]
Nothing we can really do if the format you want doesn't exist. Excel should auto-detect the format, according to [this stackoverflow post](http://superuser.com/a/318421).

Sorry that we can't help any further.
