### ISSUE TITLE
Layout and helpers?

### ISSUE THREAD

**Issue by holisticnetworking** [FriendsOfCake/cakephp-csvview#76]
It would be especially nice to be able to use this plugin with some of my formatting helpers at my disposal.

**Comment by dereuromark** [comment]
Isnt that possible using callables/closures?

**Comment by josegonzalez** [comment]
@holisticnetworking how would you imagine that working?

**Comment by holisticnetworking** [comment]
One way might be to specify a "formatter" callable for each field. Thus $_extract might look like such:

```$_extract = [
 ['price'] => 'NumberHelper::currency'
[, 'col', 'col']
]```

**Comment by josegonzalez** [comment]
Is this something you would be interested in building? I'm not sure how the user interface would be, and as the current formatting methods work fine for me, I'm not really inclined to write it.

We can help you with tests once the pr is up.

**Comment by holisticnetworking** [comment]
What current formatting?

**Comment by holisticnetworking** [comment]
I'm looking at the code, and while there is a variable created called "formatter," really, that's just an extraction function. It does not actually format anything in the sense of NumberHelper or similar functions. I'm going to play around with this some and see what I can do.

**Comment by dereuromark** [comment]
Something like this could indeed work:
```php
$_formatters = [
    'price' => ['NumberHelper::currency' [, 'col', 'col']],
    'some_field => function ($value) { //format }
    ....
]

And then apply those callable if available prior to finally formatting the output?

**Comment by ADmad** [comment]
You are use callables in `$_extract` array to achieve whatever formatting you want for a field. The README has example for it.
