### ISSUE TITLE
Add paginator

### ISSUE THREAD

**Issue by imdad** [FriendsOfCake/cakephp-csvview#77]
It would be great if you can add _pagination support_ for CSV data. It will be a very useful feature as per end user's perspective to see the data in a paginated view like it used to see all the other data on website which comes from database.

**Comment by josegonzalez** [comment]
A CSV wouldn't be able to be interacted with via the browser. As it stands, if you land on a page that is paginated, the dataset sent to the user would be whatever is on that page. You can change this to send all the data when generating a CSV, for instance.

**Comment by dereuromark** [comment]
That is already possible and supported, see http://sandbox.dereuromark.de/sandbox/csv
E.g.
- http://sandbox.dereuromark.de/sandbox/csv/pagination.csv
- http://sandbox.dereuromark.de/sandbox/csv/pagination.csv?page=13

It should not be hard to build this for your use case yourself based on the existing paginator of CakePHP core and this CSV plugin.
