### ISSUE TITLE
Support virtual fields in $_extract list for CSV generation

### ISSUE THREAD

**Issue by JayWalker512** [FriendsOfCake/cakephp-csvview#81]
I make liberal use of virtual fields in my application for generating data on the fly, it would be nice to have access to these just like other fields when doing the setup for CSV generation. Currently I'm doing something like this:

```php
$_extract = [
    'id',
    'full_name' => function ($row) {
        return $this->Sps->get($row['id'])->full_name;
    },
    'user.email',
    'birthdate',
];
```
Which works, and I can live with it, but it would be nice to be less clunky. If this is already supported in some way, it doesn't seem to be documented.

**Comment by josegonzalez** [comment]
Interesting. I guess a virtual field isn't returned in `toArray()`: https://github.com/FriendsOfCake/cakephp-csvview/blob/master/src/View/CsvView.php#L310

**Comment by JayWalker512** [comment]
Turns out my workaround is unnecessary. You can allow virtual fields to be exported in `toArray()` by specifying the name of the virtual field in the `$_virtual` array on the entity class ala:
```php

class User extends Entity
{
    protected $_virtual = ['full_name'];
}
```
as pulled from [here in the cookbook.](https://book.cakephp.org/3.0/en/orm/entities.html#exposing-virtual-properties)

Then specifying the name of the virtual field in `$_extract` works as expected.
