### ISSUE TITLE
filename extension doesn't work in chrome browser

### ISSUE THREAD

**Issue by pieroGit** [FriendsOfCake/cakephp-csvview#86]
hi, when i download file.csv in chrome, the browser ignore file extension and download export.
The file has been created correctly, it's can be open with a text editor.
How can i resolve this problem?

**Comment by dereuromark** [comment]
This is usually not a problem of this plugin, but how you handle downloads in general, and the browser you are using.
See http://www.dereuromark.de/2011/11/21/serving-views-as-files-in-cake2/
The same applies for 3.x. So setting a specific file in the URL helps - also see the linked sandbox demos.
