### ISSUE TITLE
CSV export in cake 3.6

### ISSUE THREAD

**Issue by pitocms** [FriendsOfCake/cakephp-csvview#87]
Some methods are deprecated in cakephp 3.6 , 
example : 
Download to withDownload
Subject to getSubject
Config to getConfig
I have changed all method name but still plugin is not working in cake version 3.6.

**Comment by sdarmofal** [comment]
Hi. I had problems in cake version 3.5.12 too. I resolved it by changing *Plugin::load()* method in my *bootstrap.php* file. It should be `Plugin::load('CsvView', ['routes' => true]);`

**Comment by Isengo1989** [comment]
Same here with the newest version of 3.6

**Comment by josegonzalez** [comment]
@sdarmofal if you're talking about rendering on `.csv` extension, that routes file was added 2 years ago. Do you mind PRing a doc change?

@Isengo1989 @pitocms Pull requests to use non-deprecated methods are welcome!

**Comment by leomask101193** [comment]
Me too, issue happen when i use method withDownload in version 3.6.

**Comment by Modicrumb** [comment]
@leomask101193 did you make sure to do $this->response = $this->reponse->withDownload($filename)?

Also I have created a PR for this #92
